version: "3"
services:
  reverseproxy:
      image: hupe1980/udacity-reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: hupe1980/udacity-restapi-user
    env_file: 
      - ../../.env
    # environment:
    #   POSTGRESS_USERNAME: $POSTGRESS_USERNAME
    #   POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
    #   POSTGRESS_DB: $POSTGRESS_DB 
    #   POSTGRESS_HOST: $POSTGRESS_HOST 
    #   AWS_REGION: $AWS_REGION 
    #   AWS_PROFILE: $AWS_PROFILE 
    #   AWS_BUCKET: $AWS_BUCKET
    #   JWT_SECRET: $JWT_SECRET
    #   URL: "http://localhost:8100"
  backend-feed:
    image: hupe1980/udacity-restapi-feed
    env_file: 
      - ../../.env
    volumes:
      - $HOME/.aws:/root/.aws
    # environment:
    #   POSTGRESS_USERNAME: $POSTGRESS_USERNAME
    #   POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
    #   POSTGRESS_DB: $POSTGRESS_DB 
    #   POSTGRESS_HOST: $POSTGRESS_HOST 
    #   AWS_REGION: $AWS_REGION 
    #   AWS_PROFILE: $AWS_PROFILE 
    #   AWS_BUCKET: $AWS_BUCKET
    #   JWT_SECRET: $JWT_SECRET
    #   URL: "http://localhost:8100"
  frontend:
    image: hupe1980/udacity-frontend:local
    env_file: 
      - ../../.env
    ports:
      - "8100:80"
